# Generated by Django 4.2.6 on 2023-10-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default=1, null=True, upload_to='stockapp'),
        ),
    ]
