# Generated by Django 4.2.6 on 2023-10-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria_fk',
            field=models.CharField(choices=[('NAC', 'NACIONAL'), ('IMP', 'IMPORTADO')], default='NAC', max_length=3),
        ),
    ]
