# Generated by Django 4.2.6 on 2023-10-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_alter_productos_categoria_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='origen',
            field=models.CharField(choices=[('NAC', 'Nacional'), ('IMP', 'Importado')], default='NAC', max_length=3),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria_fk',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockapp.categorias'),
        ),
    ]
